import {COLORS,ICONS,TYPES,BOARD,BACKGROUNDS,POLICIES,GOALS,newGame,transition,actor,options,eventText,wealth,age,aiAction} from './engine.mjs';
import {URL,KEY} from './config.mjs';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=n=>Math.round(n).toLocaleString('ko-KR');
let game=null,mode='home',session=null,room=null,busy=false,animating=false,aiTimer=null,pollTimer=null,polling=false,screen='home',lastOnline=Date.now(),lastRendered=-1,queued=false,soundOn=false,audio=null;
const SAVE='newhabituslife-save-v1',SESSION='newhabituslife-room-v1';
const town=`<svg class="town" viewBox="0 0 340 155" role="img" aria-label="학교와 집, 나무가 있는 작은 보드게임 마을"><ellipse cx="170" cy="131" rx="144" ry="17" fill="#dce3cd"/><path d="M28 132 Q80 113 128 132 T241 131 T312 130" fill="none" stroke="#faf8ec" stroke-width="17"/><g stroke="#53786a" stroke-width="2"><path d="M52 110v22M292 104v27M257 115v18"/><ellipse cx="51" cy="97" rx="16" ry="24" fill="#9fbd89" stroke="none"/><ellipse cx="293" cy="89" rx="19" ry="27" fill="#7da381" stroke="none"/><circle cx="257" cy="108" r="14" fill="#b4c895" stroke="none"/></g><g><path d="M80 84h69v45H80z" fill="#f2d3b1"/><path d="M73 85l41-36 42 36z" fill="#d58061"/><path d="M106 104h17v25h-17" fill="#708d7a"/><path d="M88 94h11v12H88zM129 94h11v12h-11z" fill="#fffbdf"/><path d="M177 65h59v63h-59z" fill="#e6e4c7"/><path d="M173 59h67v12h-67z" fill="#6d9183"/><path d="M190 110h15v18h-15z" fill="#6d9183"/><path d="M188 81h11v13h-11zM215 81h11v13h-11zM215 105h11v13h-11z" fill="#a9c4b6"/><path d="M202 58V28" fill="none" stroke="#6d9183" stroke-width="2"/><path d="M203 29h22l-6 7 6 7h-22" fill="#e1b858"/><rect x="146" y="96" width="21" height="30" rx="2" fill="#e6bb72"/><path d="M142 97l15-16 15 16z" fill="#9eb2a0"/></g><path d="M21 44c0-8 12-12 17-4 9-6 19 2 14 9H22zM265 32c0-7 10-11 15-4 8-6 18 2 14 8h-29z" fill="#fffdf2"/><g fill="#ddb46e"><circle cx="73" cy="132" r="3"/><circle cx="243" cy="137" r="3"/><circle cx="310" cy="131" r="3"/></g></svg>`;
function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',3500);}
function beep(freq=500){if(!soundOn)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),v=audio.createGain();o.connect(v);v.connect(audio.destination);o.frequency.value=freq;v.gain.setValueAtTime(.035,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.start();o.stop(audio.currentTime+.13);}catch{}}
function modal(html){$('modal').innerHTML=`<button class="close" data-close aria-label="닫기">×</button>${html}`;$('modal').showModal();$('modal').querySelector('[data-close]').onclick=()=>$('modal').close();}
function header(){return `<header class="topbar"><div class="brand"><span class="brandmark">⚄</span><div>플레이하는 사회<small>PLAY SOCIETY · LIFE BOARD</small></div></div><div class="nav"><span class="pill desktop">인생 보드게임</span><button data-nav="rules">게임 방법</button><button data-nav="sound" aria-pressed="${soundOn}">${soundOn?'♪ 소리 켜짐':'♪ 소리 꺼짐'}</button>${screen!=='home'?'<button data-nav="home">처음으로</button>':''}</div></header>`;}
function footer(){return '<footer class="footer"><span>PLAY SOCIETY · 인생 한 바퀴</span><span>금액 단위: 게임머니 · 현실의 소득·투자수익·인생을 예측하는 모형이 아닙니다.</span></footer>';}
function mount(body){$('app').innerHTML=`<div class="shell">${header()}${body}${footer()}</div>`;bindCommon();}
function bindCommon(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{if(b.dataset.nav==='rules')rules();if(b.dataset.nav==='sound'){soundOn=!soundOn;b.setAttribute('aria-pressed',soundOn);b.textContent=soundOn?'♪ 소리 켜짐':'♪ 소리 꺼짐';beep();}if(b.dataset.nav==='home'){if(busy||animating){toast('말이 멈출 때까지 잠시 기다려주세요.');return;}if(session?.host&&game?.phase!=='done'){modal('<h2>진행을 잠시 멈출까요?</h2><p>이 화면을 나가면 온라인 방의 진행이 멈춥니다. 같은 브라우저에서 온라인 이어하기로 돌아올 수 있어요.</p><button id="go-home" class="primary wide">저장하고 처음으로</button>');$('go-home').onclick=()=>{$('modal').close();home();};}else home();}});document.querySelectorAll('[data-cell]').forEach(b=>{b.onclick=()=>{const t=BOARD[+b.dataset.cell];modal(`<h2>${TYPES[t][1]} ${TYPES[t][0]} 칸</h2><p>${t==='start'?'주사위만큼 이동합니다. 한 바퀴를 먼저 도는 경주가 아니라, 정해진 라운드 동안 각자의 인생을 만드는 게임이에요.':(eventText({type:t,variant:0})?.[1]||'예상하지 못한 기회를 만나세요.')}</p><p class="muted">1·2라운드는 배움, 3라운드는 진로 카드를 반드시 만납니다. 이후에는 도착한 칸의 카드를 해결해요.</p>`);};b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();b.click();}};});}
function coord(i){if(i<9)return[1,i+1];if(i<14)return[i-7,9];if(i<23)return[7,23-i];return[29-i,1];}
function board(g,preview=false){return `<div class="board" aria-label="28칸 인생 보드판">${BOARD.map((t,i)=>{let [r,c]=coord(i);let ps=g?.players.filter(p=>p.pos===i)||[];return `<div class="cell ${g?.players[g.turn]?.pos===i?'current':''}" style="grid-row:${r};grid-column:${c};--tile:${TYPES[t][2]}" data-cell="${i}" role="button" tabindex="0" aria-label="${i+1}번 ${TYPES[t][0]} 칸${ps.length?' · '+ps.map(p=>p.name).join(', '):''}"><span class="tile-no">${String(i+1).padStart(2,'0')}</span><span class="tile-icon" aria-hidden="true">${TYPES[t][1]}</span><span class="label">${TYPES[t][0]}</span><div class="pawns">${ps.map(p=>`<span class="pawn" style="--pc:${COLORS[p.id]}" title="${esc(p.name)}">${p.id+1}</span>`).join('')}</div></div>`;}).join('')}<div class="board-center"><div class="eyebrow">Every life has a story</div><div class="center-title">인생 한 바퀴</div><div class="center-sub">다른 출발선, 함께 만드는 우리 사회</div>${town}<div class="center-bottom">${preview?'<span class="pill">🎲 운과 선택</span><span class="pill">🤝 관계와 협력</span><span class="pill">⚖ 우리가 정하는 규칙</span>':`<span class="pill">공동기금 ${num(g.fund)}</span><span class="pill">${esc(g.market)}</span>`}</div>${!preview&&g.policies.length?`<div class="row" style="margin-top:8px">${g.policies.map(k=>`<span class="policy-chip">${POLICIES[k].icon} ${POLICIES[k].name}</span>`).join('')}</div>`:''}</div></div>`;}
function home(){clearTimeout(aiTimer);clearInterval(pollTimer);screen='home';mode='home';busy=false;queued=false;let demo=newGame(['여우','고래','병아리','곰'],{seed:12});demo.players.forEach((p,i)=>p.pos=[2,9,17,25][i]);let saved=readLocal(SAVE),savedRoom=readLocal(SESSION);mount(`<section class="hero"><div><span class="pill"><span class="dot"></span> 주사위 위에서 만나는 사회</span><h1>인생은 한 바퀴.<br>선택은 <em>무한가지.</em></h1><p>누구는 조금 앞에서, 누구는 다른 길에서.<br>배우고, 일하고, 서로를 도우며<br>우리만의 인생 보드게임을 시작해요.</p><div class="row" style="margin-top:24px"><button class="primary" id="quick">혼자 바로 시작하기 ↗</button>${saved?'<button id="resume">저장한 게임 이어하기</button>':''}</div><p class="note">2–6명 · 기본 8라운드 · 예상 20–35분<br>혼자 할 때는 AI 친구들이 함께해요.</p></div><div class="hero-board">${board(demo,true)}</div></section><section class="mode-grid"><button class="mode-card" data-mode="solo"><span class="mode-icon">🎲</span><div><h3>혼자, 가볍게 한 판</h3><p>AI 친구 3명과 함께.<br>선생님 없이도 바로 시작해요.</p><b>나만의 인생 시작 →</b></div></button><button class="mode-card" data-mode="local"><span class="mode-icon">🪑</span><div><h3>한 테이블에 모여서</h3><p>한 기기로 2–6팀이 돌아가며.<br>대화하고 협상하는 교실 보드게임.</p><b>테이블 만들기 →</b></div></button><button class="mode-card" data-mode="online"><span class="mode-icon">🌐</span><div><h3>각자의 화면, 같은 보드</h3><p>방 코드로 만나 함께 플레이.<br>제안과 투표가 모두의 화면에 연결돼요.</p><b>온라인 방 만들기 / 참가 →</b></div></button></section>${savedRoom?'<div style="margin-bottom:22px"><button id="resume-room" class="secondary">온라인 방 이어하기</button></div>':''}`);
 $('quick').onclick=()=>startLocal('solo',{names:['나','고래','병아리','곰'],rounds:8,equal:false});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setup(b.dataset.mode));if($('resume'))$('resume').onclick=()=>{game=saved.game;mode=saved.mode;session=null;screen='game';renderGame();scheduleAI();};if($('resume-room'))$('resume-room').onclick=()=>{session=savedRoom;mode='online';beginPoll();};
}
function readLocal(key){try{return JSON.parse(localStorage.getItem(key));}catch{return null;}}
function persist(){if(['solo','local'].includes(mode)&&game)try{localStorage.setItem(SAVE,JSON.stringify({mode,game}));}catch{toast('브라우저 저장 공간이 부족합니다.');}}
function setup(kind){screen='setup';mount(`<section class="setup panel"><span class="eyebrow">Set your table</span><h1 style="margin-top:10px">${kind==='online'?'같은 보드에서 만나요':kind==='solo'?'나의 첫 주사위':'오늘의 테이블 만들기'}</h1><p class="muted small">${kind==='online'?'진행자는 방을 만들고, 참가자는 6자리 코드를 입력하세요.':'별명으로 시작하세요. 캐릭터의 출발 조건은 게임 속 가상의 설정입니다.'}</p>${kind==='online'?`<label for="online-name">내 별명 / 모둠 이름</label><input id="online-name" maxlength="12" placeholder="예: 1모둠"><div class="fields"><div><label for="online-code">참가할 방 코드</label><input id="online-code" maxlength="6" placeholder="6자리 코드" autocomplete="off" style="text-transform:uppercase"></div><div style="align-self:end"><button id="join-room" class="secondary wide">코드로 참가하기</button></div></div><button id="create-room" class="primary wide">새 온라인 방 만들기</button><div class="hint">2–6팀 · 진행자도 한 팀으로 참여합니다. 진행자 화면을 켜 두어야 게임이 진행돼요. 방은 7일 동안 이어할 수 있어요.</div>`:`<div class="fields"><div><label for="count">참가 팀 수</label><select id="count">${[2,3,4,5,6].map(n=>`<option ${n===4?'selected':''}>${n}</option>`).join('')}</select></div><div><label for="rounds">게임 길이</label><select id="rounds"><option value="8">가볍게 · 8라운드</option><option value="12">깊이 있게 · 12라운드</option></select></div></div><label>플레이어 이름 ${kind==='solo'?'(첫 번째가 나, 나머지는 AI)':''}</label><div id="names" class="names"></div><label class="check"><input type="checkbox" id="equal">비교 실험: 모두 같은 출발 조건</label><button id="start" class="primary wide">출발선 뽑고 시작하기 →</button><div class="hint">모두가 같은 횟수만큼 플레이합니다. 자산뿐 아니라 건강, 배움, 도움의 기록도 마지막에 함께 돌아봐요.</div>`}<div id="setup-error" role="alert"></div></section>`);
 if(kind==='online'){$('create-room').onclick=()=>connect('create');$('join-room').onclick=()=>connect('join');return;}
 const names=()=>{$('names').innerHTML=Array.from({length:+$('count').value},(_,i)=>`<input aria-label="${i+1}번 플레이어 이름" maxlength="12" value="${kind==='solo'?['나','고래','병아리','곰','토끼','거북이'][i]:`${i+1}모둠`}">`).join('');};names();$('count').onchange=names;$('start').onclick=()=>startLocal(kind,{names:[...$('names').querySelectorAll('input')].map(i=>i.value),rounds:+$('rounds').value,equal:$('equal').checked});
}
function startLocal(kind,opts){clearInterval(pollTimer);session=null;mode=kind;screen='game';game=newGame(opts.names,{rounds:opts.rounds,equal:opts.equal,ai:kind==='solo'?opts.names.map((_,i)=>i).slice(1):[]});persist();renderGame();intro();}
function intro(){modal(`<h2>출발선이 정해졌어요</h2><p>이 조건은 캐릭터의 가상 배경입니다. 실제 여러분의 가정과는 관계없어요.</p>${game.players.map(p=>`<div class="room-member"><span style="font-size:25px">${ICONS[p.id]}</span><div><b>${esc(p.name)}</b> · 시작 ${num(p.born)}<div class="muted small">${BACKGROUNDS[p.background].name} · ${esc(p.cards.join(' · '))}</div></div></div>`).join('')}<p class="small">먼저 도착하는 경주가 아닙니다. 모두 ${game.maxRounds}번의 선택을 하고, 각자의 삶을 돌아봐요.</p><button id="intro-close" class="primary wide">좋아, 나의 인생을 시작하자</button>`);$('intro-close').onclick=()=>{$('modal').close();scheduleAI();};}
function playerPanel(p){return `<button class="player ${game.turn===p.id?'active':''}" style="--pc:${COLORS[p.id]}" data-player="${p.id}" aria-label="${esc(p.name)} 상태 보기"><div class="row spread"><div class="row" style="gap:7px"><span class="avatar">${ICONS[p.id]}</span><span class="player-name">${esc(p.name)}${p.ai?' · AI':''}</span></div>${game.turn===p.id?'<span style="font-size:9px">MY TURN</span>':''}</div><div class="money" style="margin-top:8px">${num(p.cash)} <small>현금</small></div><div class="mini-stats"><span>♥ ${p.health}/6</span><span>역량 ${p.skill}</span><span>신뢰 ${p.trust}</span></div></button>`;}
function canAct(id=actor(game)){if(busy||animating||queued)return false;if(mode==='online')return session?.seat===id;return !game.players[id]?.ai;}
function renderGame(){screen='game';if(game.phase==='done')return results();let p=game.players[game.turn];mount(`<div class="game-head row spread"><div><div class="eyebrow">Life is a board game</div><h1>인생 한 바퀴</h1></div><div class="round-meta">${session?`<span class="pill">방 ${session.code}</span>`:'<span class="pill">'+(mode==='solo'?'AI와 함께':'한 테이블 플레이')+'</span>'}<div class="round-num">${game.round}<span> / ${game.maxRounds} ROUND</span></div><span class="pill">${age(game)}세</span></div></div><div class="players" style="--count:${game.players.length}">${game.players.map(playerPanel).join('')}</div><div class="game-grid"><div class="board-wrap"><div id="board-host">${board(game)}</div><div class="board-caption"><div class="legend">${['learn','network','market','care','community'].map(t=>`<span><i style="background:${TYPES[t][2]};border:1px solid #aaa7"></i>${TYPES[t][0]}</span>`).join('')}</div><span>칸을 누르면 설명을 볼 수 있어요</span></div><div class="timeline" aria-label="라운드 진행">${Array.from({length:game.maxRounds},(_,i)=>`<i class="${i<game.round?'on':''}"></i>`).join('')}</div><section class="journal"><div class="row spread"><h3>우리 테이블의 이야기</h3><span class="small muted">최근 기록</span></div><div class="log-list" aria-live="polite">${game.log.slice(0,10).map(l=>`<div class="log-item"><span>R${l.round}</span><div>${esc(l.text)}</div></div>`).join('')}</div></section></div><aside class="control"><section class="panel fade-in"><div class="turn-tag"><span class="avatar">${ICONS[p.id]}</span><span>${esc(p.name)}의 차례</span>${p.ai?'<span class="pill">AI</span>':''}</div><div id="actions">${actionPanel()}</div></section><div class="hint">${game.phase==='vote'?'정책을 고르면 비용도 함께 부담합니다. 누가 혜택을 받고, 누가 더 부담하는지 이야기해보세요.':game.round<3?'첫 두 라운드는 배움, 세 번째는 진로 선택입니다. 이후에는 도착한 칸에서 새로운 인생 카드를 만나요.':'다른 사람의 선택도 내 삶에 영향을 줍니다. 도움은 의무가 아니에요. 제안을 받아도 거절할 수 있습니다.'}</div><div class="row spread" style="margin-top:13px"><button id="my-info" class="small">내 카드 · 목표</button><span class="network-status" id="net-status">${mode==='online'?'온라인 연결됨':'이 기기에 자동 저장'}</span></div>${session?.host?'<button class="small wide" style="margin-top:10px" id="assist">진행자: 멈춘 차례 도와주기</button>':''}</aside></div><div style="height:28px"></div>`);bindGame();}
function actionPanel(){const p=game.players[game.turn],id=actor(game),active=game.players[id],can=canAct();let wait=mode==='online'&&id!==session.seat?`<p class="muted small" style="margin-top:12px">${esc(active?.name||'다른 팀')}의 선택을 기다리고 있어요.</p>`:'';
 if(game.phase==='roll')return `<h2>어떤 하루가 기다릴까요?</h2><p class="desc">주사위를 굴리고, 말이 도착한 곳에서 나의 선택을 시작하세요.</p><div class="dice-area"><div class="dice" id="dice" aria-label="주사위">⚄</div><button class="primary wide roll-button" data-action="roll" ${can?'':'disabled'}>${p.ai?'AI가 생각하는 중…':'주사위 굴리기'}</button></div>${wait}`;
 if(game.phase==='choice'){const [title,desc]=eventText(game.event);return `<span class="event-icon">${TYPES[game.event.type][1]}</span><div class="eyebrow">${game.die}칸 이동 · ${TYPES[game.event.type][0]}</div><h2 style="margin-top:6px">${title}</h2><p class="desc">${desc}</p><div class="options">${options(game).map(o=>`<button class="choice" data-action="choose" data-value="${o.id}" ${can&&!o.disabled?'':'disabled'}><b>${o.title}${o.disabled?' 🔒':''}</b><span>${o.desc}</span></button>`).join('')}</div>${wait}`;}
 if(game.phase==='target')return `<h2>누구에게 제안할까요?</h2><p class="desc">${game.pending==='ask'?'돌봄 도움을 부탁해보세요. 상대가 수락해야 성사됩니다.':'함께 100씩 투자할 동료를 찾아보세요. 손익도 함께 나눕니다.'}</p><div class="options">${game.players.filter(q=>q.id!==p.id).map(q=>`<button class="choice" data-action="target" data-value="${q.id}" ${can&&q.cash>=(game.pending==='ask'?60:100)?'':'disabled'}><b>${ICONS[q.id]} ${esc(q.name)}</b><span>현재 현금 ${num(q.cash)}</span></button>`).join('')}</div><button data-action="target" data-value="cancel" style="margin-top:10px" ${can?'':'disabled'}>돌아가기</button>${wait}`;
 if(game.phase==='offer')return `<span class="event-icon">🤝</span><h2>${esc(active.name)}님, 제안이 왔어요</h2><p class="desc">${esc(p.name)}${game.offer.kind==='ask'?'이 돌봄 도움을 요청했어요. 수락하면 내 현금 60을 쓰고 두 사람 신뢰가 1씩 올라요.':'이 공동사업을 제안했어요. 각자 100이 필요하며, 35% 확률로 50 손실·65% 확률로 90 이익을 함께 얻어요.'}</p><div class="row"><button class="primary" data-action="respond" data-value="yes" ${can?'':'disabled'}>함께할게요</button><button data-action="respond" data-value="no" ${can?'':'disabled'}>이번엔 어려워요</button></div>${wait}`;
 if(game.phase==='vote'){const me=mode==='online'?session.seat:id,voted=game.votes[me]!==undefined;return `<span class="event-icon">⚖</span><h2>우리가 만드는 다음 사회</h2><p class="desc">정책 한 가지에 투표하세요. 최다 득표 정책을 시행하며, 동률이면 현행을 유지합니다. 정책마다 이후 소득의 10%를 공동기금으로 냅니다.</p><p class="small" style="margin-bottom:10px">${Object.keys(game.votes).length} / ${game.players.length}팀 투표 · ${voted?'투표 완료':esc(game.players[me]?.name)+'의 투표'}</p><div class="options">${Object.entries(POLICIES).filter(([k])=>!game.policies.includes(k)).map(([k,v])=>`<button class="choice" data-action="vote" data-value="${k}" ${!voted&&!busy&&!queued&&(mode==='online'||can)?'':'disabled'}><b>${v.icon} ${v.name}</b><span>${v.desc}</span></button>`).join('')}<button class="choice" data-action="vote" data-value="none" ${!voted&&!busy&&!queued&&(mode==='online'||can)?'':'disabled'}><b>현행 유지</b><span>새로운 세금과 지원 제도를 추가하지 않아요.</span></button></div>`;}
 return `<div class="success-mark">✓</div><h2>내 인생에 한 줄이 더해졌어요</h2><p class="desc">${esc(game.log[0]?.text||'선택이 기록되었습니다.')}</p><div class="ledger"><div class="row spread"><span>지금 현금</span><b>${num(p.cash)}</b></div><div class="row spread"><span>순자산 (현금+투자+집−대출)</span><b>${num(wealth(p))}</b></div><div class="row spread"><span>건강 / 역량 / 신뢰</span><b>${p.health} / ${p.skill} / ${p.trust}</b></div>${p.debt?`<div class="row spread"><span>대출 잔액</span><b>${num(p.debt)}</b></div>`:''}</div><button class="primary wide" data-action="next" ${can?'':'disabled'}>${game.turn===game.players.length-1?'이번 라운드 마무리 →':'다음 플레이어에게 →'}</button>${wait}`;
}
function bindGame(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{let v=b.dataset.value;if(b.dataset.action==='target'&&v!=='cancel')v=+v;let id=game.phase==='vote'&&mode==='online'?session.seat:actor(game);dispatch({type:b.dataset.action,value:v,actor:id,expected:game.revision,round:game.round});});document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>info(+b.dataset.player));$('my-info').onclick=()=>info(mode==='online'?session.seat:mode==='solo'?0:game.turn);if($('assist'))$('assist').onclick=()=>{modal('<h2>현재 차례를 도와줄까요?</h2><p>연결이 끊겼거나 오래 멈춘 팀의 이번 행동 한 번을 AI 제안으로 처리합니다. 해당 팀과 먼저 이야기해주세요.</p><button id="assist-confirm" class="primary wide">이번 행동 한 번 진행</button>');$('assist-confirm').onclick=async()=>{$('modal').close();if(busy)return;await hostAction(aiAction(game));};};}
function info(id){const p=game.players[id];modal(`<h2>${ICONS[id]} ${esc(p.name)}의 인생 카드</h2><p><b>${BACKGROUNDS[p.background].name}</b><br>${BACKGROUNDS[p.background].desc}</p><div class="ledger"><div class="row spread"><span>출발 자금 → 현재 순자산</span><b>${num(p.born)} → ${num(wealth(p))}</b></div><div class="row spread"><span>직업 / 턴당 소득</span><b>${p.job} / ${num(p.salary)}</b></div><div class="row spread"><span>투자 / 주택 / 대출</span><b>${num(p.stocks)} / ${num(p.home)} / ${num(p.debt)}</b></div></div><p><b>만남 카드</b></p>${p.cards.map(c=>`<span class="badge">${c}</span>`).join('')}<p class="small muted">친구: 돌봄 할인·물건 빌리기 / 멘토·동문: 기회 지원 조건</p><div class="info"><b>나의 목표 · ${GOALS[p.goal].name}</b><br>${GOALS[p.goal].desc}</div><p class="small">건강은 최대 6입니다. 0이면 소득이 절반이지만 탈락하지 않아요. 순자산이 마이너스여도 끝까지 함께 플레이합니다.</p>`);}
async function animate(old,next){if(next.phase!=='choice'||old.phase!=='roll'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;animating=true;const dice=$('dice');if(dice){dice.classList.add('rolling');for(let i=0;i<6;i++){dice.textContent=['⚀','⚁','⚂','⚃','⚄','⚅'][i];beep(260+i*80);await new Promise(r=>setTimeout(r,70));}dice.classList.remove('rolling');dice.textContent=['⚀','⚁','⚂','⚃','⚄','⚅'][next.die-1];}let tmp=structuredClone(old);for(let i=1;i<=next.die;i++){tmp.players[tmp.turn].pos=(old.players[old.turn].pos+i)%28;if($('board-host'))$('board-host').innerHTML=board(tmp);await new Promise(r=>setTimeout(r,100));}animating=false;}
async function dispatch(action){if(busy||queued||animating)return;busy=true;document.querySelectorAll('[data-action]').forEach(b=>b.disabled=true);try{if(mode==='online'){await rpc('send',{action,nonce:crypto.randomUUID()});queued=true;toast('선택을 보냈어요. 진행자 화면과 연결 중입니다.');}else{let next=transition(game,action);await animate(game,next);game=next;persist();beep(650);}}catch(e){toast(e.message);}finally{busy=false;if(mode!=='online'||!queued)renderGame();scheduleAI();}}
function scheduleAI(){clearTimeout(aiTimer);if(mode==='home'||screen!=='game'||!game||game.phase==='done'||busy||animating)return;if(game.players[actor(game)]?.ai)aiTimer=setTimeout(()=>{if(mode==='online')return;dispatch(aiAction(game));},game.phase==='result'?1300:1000);}
function results(){clearTimeout(aiTimer);screen='results';const max=Math.max(...game.players.map(wealth),...game.players.map(p=>p.born),1);mount(`<section class="results"><span class="eyebrow">Every choice leaves a trace</span><h1 style="margin-top:12px">우리의 인생은 어떤 모양이었나요?</h1><p class="muted">${game.maxRounds}라운드의 선택이 모였습니다. 돈, 배움, 건강, 함께한 순간을 돌아봐요.</p><div class="result-grid">${game.players.map(p=>`<article class="result-card" style="--pc:${COLORS[p.id]}"><h3>${ICONS[p.id]} ${esc(p.name)}</h3><p class="small muted">${p.job}</p><div class="money">${num(wealth(p))} <small>최종 순자산</small></div><p class="small">출발 ${num(p.born)} → 변화 ${wealth(p)-p.born>=0?'+':''}${num(wealth(p)-p.born)}</p><p class="small" style="margin-top:7px">♥ 건강 ${p.health}/6 · 역량 ${p.skill} · 도움 ${p.help}회</p><div class="goal">${GOALS[p.goal].check(p)?'✓ 목표 달성':'◇ 다음 인생의 목표'}<br><b>${GOALS[p.goal].name}</b><br>${GOALS[p.goal].desc}</div></article>`).join('')}</div><section class="panel"><h2>출발선과 도착선</h2><p class="small muted">연한 막대: 출발 자금 · 진한 막대: 최종 순자산 (음수는 숫자로 표시)</p><div class="bars">${game.players.map(p=>`<div class="bar-row" style="--pc:${COLORS[p.id]}"><b>${esc(p.name)}</b><div class="bar-pair"><i style="width:${p.born/max*100}%"></i><i style="width:${Math.max(0,wealth(p))/max*100}%"></i></div><span>${num(wealth(p))}</span></div>`).join('')}</div><p class="small muted">이 결과는 이번 게임의 규칙과 선택에서 나왔습니다. 현실 사회의 인과관계나 자녀의 미래 자산을 뜻하지 않아요.</p></section><section class="reflection" style="margin-top:20px"><h2>주사위를 내려놓고, 이야기해요.</h2><ol><li>하고 싶었지만 조건 때문에 선택하지 못했던 것은 무엇인가요?</li><li>누군가의 도움이나 정보가 내 선택을 바꾼 순간이 있었나요?</li><li>우리의 정책은 누구에게 도움이 되었고, 비용은 누가 부담했나요?</li><li>다시 한다면 나의 선택과 사회의 규칙 중 무엇을 바꾸고 싶나요?</li></ol></section><div class="row" style="margin:22px 0"><button id="export" class="primary">플레이 기록 내려받기</button><button id="print-result">결과 인쇄</button>${mode!=='online'?'<button id="replay" class="secondary">같은 친구들과 새 인생</button>':''}<button id="result-home">처음으로</button></div></section>`);$('export').onclick=exportGame;$('print-result').onclick=()=>window.print();$('result-home').onclick=home;if($('replay'))$('replay').onclick=()=>{setup(mode);};}
function exportGame(){const lines=['플레이하는 사회 — 인생 한 바퀴',`${game.maxRounds}라운드`,...game.players.flatMap(p=>['',p.name,`출발 ${p.born} / 최종 순자산 ${wealth(p)} / 건강 ${p.health} / 역량 ${p.skill} / 도움 ${p.help}회`,`목표: ${GOALS[p.goal].desc}`, ...p.choices.map(c=>`R${c.round} ${c.title}`)]),'','테이블 기록',...game.log.slice().reverse().map(l=>`R${l.round} ${l.text}`)];const a=document.createElement('a');a.href=window.URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/plain;charset=utf-8'}));a.download='인생한바퀴_플레이기록.txt';a.click();setTimeout(()=>window.URL.revokeObjectURL(a.href),1000);}
function rules(){modal(`<h2>인생 한 바퀴, 이렇게 해요</h2><ol class="rules-list"><li><b>출발선을 뽑아요.</b> 자금과 만남 카드가 다르게 시작해요.</li><li><b>주사위를 굴려요.</b> 1–6칸 이동하고 도착한 사건을 해결해요.</li><li><b>나의 선택을 해요.</b> 돈·건강·역량·관계에는 서로 다른 쓰임이 있어요.</li><li><b>다른 사람과 만나요.</b> 돌봄을 부탁하거나 공동사업을 제안해요. 상대는 거절할 수 있어요.</li><li><b>4라운드마다 사회회의.</b> 새 정책과 그 비용을 함께 결정해요. 마지막 라운드에는 회의 없이 결과를 봐요.</li><li><b>모두 같은 횟수만큼 플레이.</b> 첫 두 번은 배움, 세 번째는 진로, 그다음부터 인생 카드예요.</li></ol><p>매 턴 소득을 받고 생활비를 냅니다. 주식은 라운드마다 −18%~+22%의 공통 시장 변화, 주택은 그 변동폭의 1/3이 적용됩니다. 대출에는 라운드당 3% 이자가 붙어요.</p><p>건강 0이면 소득이 절반이지만 탈락하지 않아요. 순자산·개인 목표·도움의 기록으로 각자의 삶을 돌아봅니다.</p><p class="muted small">온라인은 진행자 화면이 게임을 진행합니다. 진행자가 나가면 일시 정지되며 같은 브라우저에서 이어할 수 있어요. 실명과 실제 가정형편은 입력하지 마세요.</p>`);}
async function rpc(op,data={},s=session){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),12000);try{const res=await fetch(`${URL}/rest/v1/rpc/nlh_room`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify({p_op:op,p_code:s?.code||'',p_token:s?.token||null,p_data:data}),signal:ctl.signal});const j=await res.json();if(!res.ok)throw Error(j.message||'연결을 확인해주세요.');return j;}catch(e){if(e.name==='AbortError')throw Error('연결이 지연되고 있어요. 잠시 후 다시 시도하세요.');throw e;}finally{clearTimeout(t);}}
async function connect(op){if(busy)return;busy=true;$('setup-error').innerHTML='';document.querySelectorAll('.setup button').forEach(b=>b.disabled=true);try{const name=$('online-name').value.trim()||'새 모둠',code=$('online-code').value.trim().toUpperCase();if(op==='join'&&!/^[A-F0-9]{6}$/.test(code))throw Error('6자리 영문·숫자 방 코드를 확인하세요.');session=await rpc(op,{name},{code});localStorage.setItem(SESSION,JSON.stringify(session));mode='online';beginPoll();}catch(e){$('setup-error').innerHTML=`<p class="error">${esc(e.message)}</p>`;document.querySelectorAll('.setup button').forEach(b=>b.disabled=false);}finally{busy=false;}}
function beginPoll(){clearInterval(pollTimer);clearTimeout(aiTimer);room=null;lastRendered=-1;queued=false;game=null;screen='lobby';mount('<section class="setup panel"><h2>우리 테이블에 연결하는 중…</h2><p class="desc">잠시만 기다려주세요.</p><div id="connection-error"></div></section>');poll();pollTimer=setInterval(poll,1800);}
async function poll(){if(polling||busy||animating||mode!=='online')return;polling=true;try{const r=await rpc('read');if(mode!=='online')return;lastOnline=Date.now();room=r;const prior=game;game=r.state.phase==='lobby'?null:r.state;if(lastRendered!==r.version){queued=false;lastRendered=r.version;if(game){if(prior&&prior.revision!==game.revision)await animate(prior,game);renderGame();}else lobby();}
 if(session.host&&game&&game.phase!=='done'){
  const pending=r.pending?.[0];if(pending){let next=game;try{next=transition(game,pending.action);}catch(e){toast('처리되지 않은 선택: '+e.message);}await commit(next,pending.id);}
  else if(game.players[actor(game)]?.ai){await commit(transition(game,aiAction(game)));}
 }
 if($('net-status'))$('net-status').textContent=session.host?'진행자 · 온라인 연결됨':Date.now()-new Date(r.updated).getTime()>20000?'진행자 연결을 기다리는 중':'온라인 연결됨';
 }catch(e){if($('connection-error'))$('connection-error').innerHTML=`<p class="error">${esc(e.message)}</p><button id="back-connection">처음으로</button>`;if($('back-connection'))$('back-connection').onclick=home;if($('net-status'))$('net-status').textContent='연결 재시도 중 · 선택은 잠시 기다려주세요';if(Date.now()-lastOnline>12000)queued=false;}finally{polling=false;}}
function lobby(){screen='lobby';mount(`<section class="setup panel"><span class="eyebrow">Your table is ready</span><h1 style="margin-top:10px">친구들을 초대하세요</h1><div class="room-code">${esc(session.code)}</div><div class="row"><button id="copy-code">방 코드 복사</button><button id="copy-link">초대 링크 복사</button><span class="pill">${room.members.length} / 6팀</span></div><div style="margin-top:18px">${room.members.map(m=>`<div class="room-member"><span style="font-size:24px">${ICONS[m.seat]}</span><b>${esc(m.name)}</b><span class="muted small">${m.seat===0?'진행자':m.seat===session.seat?'나':'참가 완료'}</span></div>`).join('')}</div>${session.host?`<label for="online-rounds">게임 길이</label><select id="online-rounds"><option value="8">기본 8라운드</option><option value="12">확장 12라운드</option></select><label class="check"><input id="online-equal" type="checkbox">모두 같은 출발 조건</label><button class="primary wide" id="start-online" ${room.members.length<2?'disabled':''}>${room.members.length<2?'친구 한 팀이 더 필요해요':'모두 모였어요 · 게임 시작'}</button><div class="hint">게임 중 이 화면을 켜 두세요. 진행자가 화면을 나가면 진행이 멈춥니다.</div>`:'<p class="info" style="margin-top:20px">입장 완료! 진행자가 게임을 시작하면 보드판이 열립니다.</p>'}</section>`);$('copy-code').onclick=()=>copy(session.code);$('copy-link').onclick=()=>location.protocol==='file:'?toast('이 HTML 파일과 방 코드를 친구에게 공유해주세요.'):copy(location.origin+location.pathname+'?room='+session.code);if($('start-online'))$('start-online').onclick=async()=>{if(busy)return;busy=true;const rounds=+$('online-rounds').value,equal=$('online-equal').checked;try{const fresh=await rpc('read');room=fresh;if(fresh.state.phase!=='lobby')return;const g=newGame(fresh.members.map(m=>m.name),{rounds,equal});await commit(g);}catch(e){toast(e.message);}finally{busy=false;if(game)renderGame();}};}
async function commit(next,ack){const r=await rpc('commit',{version:room.version,state:next,...(ack?{ack}: {})});if(game)await animate(game,next);room=r;game=r.state;lastRendered=r.version;queued=false;renderGame();}
async function hostAction(a){if(!session?.host||busy)return;busy=true;try{room=await rpc('read');game=room.state;await commit(transition(game,{...a,expected:game.revision}));}catch(e){toast(e.message);}finally{busy=false;if(game)renderGame();}}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('복사했어요. 친구에게 알려주세요.');}catch{modal(`<h2>복사할 내용</h2><p style="word-break:break-all;user-select:all">${esc(text)}</p>`);}}
window.addEventListener('beforeunload',persist);home();const invite=new window.URLSearchParams(location.search).get('room');if(invite){setup('online');$('online-code').value=invite.slice(0,6);}
